M48
; DRILL file {KiCad 7.0.6+dfsg-1} date Wed 23 Aug 2023 02:28:12 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-23T14:28:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X52.503Y-43.0
X52.503Y-198.0
X244.497Y-43.0
X244.497Y-198.0
T0
M30
