M48
; DRILL file {KiCad 7.0.6+dfsg-1} date Thu 24 Aug 2023 06:37:57 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-24T18:37:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X24.593Y-37.315
X24.593Y-232.255
X275.033Y-37.315
X275.033Y-232.255
T0
M30
